# Generated by Django 5.2.7 on 2025-10-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='doggy',
            name='name',
        ),
    ]
