services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    restart: always
    volumes:
       - ./staticfiles:/app/staticfiles
    ports:
       - "8000:8000"
    environment:
       - DB_HOST=db # Reference environment variable from .env file
       - DB_NAME=${DB_NAME}
       - DB_USER=${DB_USER}
       - DB_PASSWORD=${DB_PASSWORD}
       - SECRET_KEY=${SECRET_KEY}
       - DEBUG=${DEBUG}
       - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
       - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    depends_on:
       - db # Make sure the database service starts first
    env_file:
       - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 stroll.wsgi:application"
  db:
    image: mysql:8.0.41
    volumes:
       - mysql_db:/var/lib/mysql # Persist the database data
    environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Use the root password from .env file
       - MYSQL_DATABASE=${DB_NAME} # The database name from .env file
    ports:
       - "3306:3306" # MySQL default port
    env_file:
       - .env

volumes:
  mysql_db: # Named volume for MySQL data persistence
