services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    restart: always
    volumes:
       - ./staticfiles:/app/staticfiles
       - ./app:/app
    ports:
       - "8000:8000"
    environment:
       - DB_HOST=${DB_HOST} # Reference environment variable from .env file
       - DB_NAME=${DB_NAME}
       - DB_USER=${DB_USER}
       - DB_PASSWORD=${DB_PASSWORD}
       - SECRET_KEY=${SECRET_KEY}
       - DEBUG=${DEBUG}
       - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
       - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    env_file:
       - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 djangoproject.wsgi:application"
